apiVersion: v1
kind: Pod
metadata:
  name: storage-monitor
spec:
  containers:
    - name: monitor
      image: busybox:1.37
      command:
        - sh
        - -c
        - |
          while true
          do
            echo "========== $(date) =========="
            echo
            echo "Disk Usage"
            df -h /data
            echo
            echo "File Count"
            find /data -type f | wc -l
            echo
            echo "Newest Files"
            ls -lt /data | head -5
            echo
            sleep 60
          done
      volumeMounts:
        - name: storage
          mountPath: /data
  restartPolicy: Always
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: local-pvc
