kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

networking:
  podSubnet: "10.242.0.0/16"
  serviceSubnet: "10.243.0.0/16"
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6444
  disableDefaultCNI: false

nodes:
  - role: control-plane
    labels:
      cloud: gcp
      region: us-central1

  - role: worker
    labels:
      cloud: gcp
      region: us-central1

  - role: worker
    labels:
      cloud: gcp
      region: us-central1
