apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
  namespace: secure-namespace
spec:
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      runAsUser: 0
      privileged: true
    ports:
    - containerPort: 80
